# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Workflow for build, test and deploy to EC2 instance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install streamlit pandas flake8 pytest
        if [ -f fishacademy-app/requirements.txt ]; then pip install -r fishacademy-app/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r fishacademy.zip fishacademy-app resources
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ns36460.ip-87-98-218.eu
        username: ubuntu
        key: ${{ secrets.KS_PRIVATE_PEM }}
        source: "fishacademy.zip"
        target: /home/ubuntu/docker
